# Generated by Django 5.2.3 on 2025-06-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(verbose_name='Automobilio marke')),
                ('modelis', models.CharField(verbose_name='Automobilio modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Iveskite paslaugos pavadinimas', max_length=100, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(verbose_name='Valsybinis numeris')),
                ('vin_kodas', models.CharField(max_length=20, verbose_name='VIN')),
                ('klientas', models.CharField(help_text='Iveskite Fizini ar Juridini asmeni', verbose_name='Klientas')),
                ('modelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobiliomodelis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(verbose_name='Uzsakymo data')),
                ('suma', models.CharField(verbose_name='Suma')),
                ('automobilis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(verbose_name='Kiekis')),
                ('kaina', models.CharField(verbose_name='Kaina')),
                ('paslauga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.uzsakymas')),
            ],
        ),
    ]
